apiVersion: v2
name: hoomail
description: A Helm chart for the Hoomail development email server
type: application
version: 0.7.0
appVersion: "0.7.0"
home: https://github.com/openhoo/hoomail
sources:
  - https://github.com/openhoo/hoomail
keywords:
  - email
  - smtp
  - pop3
  - development
maintainers:
  - name: openhoo
    url: https://github.com/openhoo
